const inputEl = document.getElementById('input');
const previewFrame = document.getElementById('preview');

const memoryKey = 'webai_memory';

function generateSite() {
  const userInput = inputEl.value.trim();
  if (!userInput) return alert("Type something!");

  // Store memory
  const memory = JSON.parse(localStorage.getItem(memoryKey)) || [];
  memory.push(userInput);
  localStorage.setItem(memoryKey, JSON.stringify(memory));

  // Basic AI-style template generation logic
  const page = generateHTML(userInput);
  previewFrame.srcdoc = page;
}

function clearMemory() {
  localStorage.removeItem(memoryKey);
  alert("Memory cleared!");
}

function generateHTML(input) {
  const title = input.match(/title\s*[:\-]\s*(.+)/i)?.[1] || "My Smart Website";
  const color = input.match(/color\s*[:\-]\s*(#[0-9a-fA-F]{3,6}|[a-z]+)/i)?.[1] || "#333";
  const font = input.match(/font\s*[:\-]\s*([a-zA-Z ,]+)/i)?.[1] || "Arial, sans-serif";

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body {
          background-color: white;
          color: ${color};
          font-family: ${font};
          padding: 2em;
        }
        h1 {
          border-bottom: 2px solid ${color};
        }
      </style>
      <script>
        console.log("Hello from your AI-generated site!");
      </script>
    </head>
    <body>
      <h1>${title}</h1>
      <p>This page was generated by your smart WebAI assistant. ✨</p>
    </body>
    </html>
  `;
  return html;
}